# Generated by Django 3.2.8 on 2022-02-12 11:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ID_name', models.CharField(max_length=20)),
                ('Receivingـunit', models.CharField(choices=[('FANI', 'فنی'), ('FORUSH', 'فروش'), ('POS', 'POS'), ('OTHERUNIT', 'سایر واحدها')], max_length=12)),
                ('Typeـservice', models.CharField(choices=[('POS', 'POS'), ('Internet', 'Internet')], max_length=30)),
                ('Userـtype', models.CharField(choices=[('HOMEUSER', 'کاربر حقیقی(خانگی)'), ('ORGANIZATIONALUSER', 'کاربر حقوقی(سازمانی)')], max_length=30)),
                ('obtain', models.CharField(choices=[('JALASE', 'جلسه'), ('HOZURI', 'حضوری'), ('TELEFONI', 'تلفنی'), ('ONLINE', 'آنلاین')], max_length=30)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Mobile_number', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
                ('ID_customer', models.CharField(max_length=10)),
                ('Reason_complaint', multiselectfield.db.fields.MultiSelectField(choices=[('ETMAMTERAFIK', 'اتمام سریع ترافیک'), ('HESABDARI', 'حسابداری'), ('NOIZE', 'نویز خط'), ('GHAT&VASLI', 'قطع و وصلی'), ('KONDISORAT', 'کندی سرعت'), ('SIMBANI', 'سیمبانی'), ('NAMAYANDEGAN', 'نمایندگان'), ('TAJHIZAT', 'تجهیزات'), ('POSHTIBANI', 'پشتیبانی روزهای تعطیل'), ('BAZNASHODAN', 'باز نشدن صفحات وب'), ('ETELAERESANI', 'عدم اطلاع رسانی'), ('MOSHKELAT', 'مشکلات دستگاه کارتخوان و خدماتش و دیر نصب شدن دستگاه'), ('NASBINTERNET', 'طولانی شدن نصب اینترنت'), ('WEBSITE', 'مشکلات وب سایت'), ('JAMAVARI', 'عدم جمع اوری'), ('OTHER', 'سایر')], max_length=162)),
                ('Complaint_description', models.TextField(max_length=200)),
                ('suggestion', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شکابت',
                'verbose_name_plural': 'شکایات',
            },
        ),
    ]
