# Generated by Django 3.2.8 on 2022-02-12 11:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ID_customer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Reason_complaint',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('اتمام سریع ترافیک', 'اتمام سریع ترافیک'), ('حسابداری', 'حسابداری'), ('نویز خط', 'نویز خط'), ('قطع و وصلی', 'قطع و وصلی'), ('کندی سرعت', 'کندی سرعت'), ('سیمبانی', 'سیمبانی'), ('نمایندگان', 'نمایندگان'), ('تجهیزات', 'تجهیزات'), ('پشتیبانی روزهای تعطیل', 'پشتیبانی روزهای تعطیل'), ('باز نشدن صفحات وب', 'باز نشدن صفحات وب'), ('عدم اطلاع رسانی', 'عدم اطلاع رسانی'), ('مشکلات دستگاه کارتخوان و خدماتش و دیر نصب شدن دستگاه', 'مشکلات دستگاه کارتخوان و خدماتش و دیر نصب شدن دستگاه'), ('طولانی شدن نصب اینترنت', 'طولانی شدن نصب اینترنت'), ('مشکلات وب سایت', 'مشکلات وب سایت'), ('عدم جمع اوری', 'عدم جمع اوری'), ('سایر', 'سایر')], max_length=246, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Receivingـunit',
            field=models.CharField(choices=[('فنی', 'فنی'), ('فروش', 'فروش'), ('POS', 'POS'), ('سایر واحدها', 'سایر واحدها')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Userـtype',
            field=models.CharField(choices=[('کاربر حقیقی(خانگی)', 'کاربر حقیقی(خانگی)'), ('کاربر حقوقی(سازمانی)', 'کاربر حقوقی(سازمانی)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='obtain',
            field=models.CharField(choices=[('جلسه', 'جلسه'), ('حضوری', 'حضوری'), ('تلفنی', 'تلفنی'), ('آنلاین', 'آنلاین')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suggestion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
