# Generated by Django 3.2.8 on 2022-02-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20220212_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
