# Generated by Django 3.2.8 on 2022-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_alter_complaint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Userـtype',
            field=models.CharField(choices=[('کاربر حقیقی(خانگی)', 'حقیقی'), ('کاربر حقوقی(سازمانی)', 'حقوقی')], max_length=30),
        ),
    ]
