# Generated by Django 3.2.8 on 2022-02-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_userـtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Userـtype',
            field=models.CharField(choices=[('کاربر حقیقی(خانگی)', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=30),
        ),
    ]
