# Generated by Django 3.2.8 on 2022-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_userـtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Userـtype',
            field=models.CharField(choices=[('کاربر حقیقی(خانگی)', 'حقیقی'), ('HOGHUGHI', 'حقوقی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='obtain',
            field=models.CharField(choices=[('جلسه', 'جلسه'), ('حضوری', 'حضوری'), ('تلفنی', 'تلفنی'), ('ONLINE', 'آنلاین')], max_length=30),
        ),
    ]
