# Generated by Django 3.2.8 on 2022-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20220213_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Userـtype',
            field=models.CharField(choices=[('کاربر حقیقی(خانگی)', 'حقیقی'), ('کاربر حقوقی(سازمانی)', 'کاربر حقوقی(سازمانی)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='obtain',
            field=models.CharField(choices=[('جلسه', 'جلسه'), ('حضوری', 'حضوری'), ('تلفنی', 'تلفنی'), ('آنلاین', 'آنلاین')], max_length=30),
        ),
    ]
