# Generated by Django 4.0.2 on 2022-02-14 05:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20220213_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ID_customer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Reason_complaint',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اتمام سریع ترافیک', 'اتمام سریع ترافیک'), ('حسابداری', 'حسابداری'), ('نویز خط', 'نویز خط'), ('قطع و وصلی', 'قطع و وصلی'), ('کندی سرعت', 'کندی سرعت'), ('سیمبانی', 'سیمبانی'), ('نمایندگان', 'نمایندگان'), ('تجهیزات', 'تجهیزات'), ('پشتیبانی روزهای تعطیل', 'پشتیبانی روزهای تعطیل'), ('باز نشدن صفحات وب', 'باز نشدن صفحات وب'), ('عدم اطلاع رسانی', 'عدم اطلاع رسانی'), ('مشکلات دستگاه کارتخوان و خدماتش و دیر نصب شدن دستگاه', 'مشکلات دستگاه کارتخوان و خدماتش و دیر نصب شدن دستگاه'), ('طولانی شدن نصب اینترنت', 'طولانی شدن نصب اینترنت'), ('مشکلات وب سایت', 'مشکلات وب سایت'), ('عدم جمع اوری', 'عدم جمع اوری'), ('سایر', 'سایر')], max_length=246),
        ),
    ]
